# Generated by Django 4.0.6 on 2022-07-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, unique=True)),
                ('sigla', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, unique=True)),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Cep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, unique=True)),
                ('logradouro', models.CharField(max_length=256)),
                ('bairro', models.CharField(max_length=256)),
                ('cidade_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.cidade')),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.estado')),
            ],
            options={
                'unique_together': {('cidade_id', 'estado_id')},
            },
        ),
    ]
